version: '3.2'

services:
  frontend:
    container_name: hw-02-frontend
    build:
      context: .
      dockerfile: .deploy/docker/frontend/Dockerfile
    volumes:
      - ./.deploy/docker/frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    depends_on:
      - backend
    ports:
      - 8030:80
  
  backend:
    container_name: hw-02-backend
    build:
      context: .
      dockerfile: .deploy/docker/backend/Dockerfile
    volumes:
      - .:/app
      
  
